# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a50-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a505f,$(TARGET_DEVICE)),)

endif
